allowBuilds:
  "@vscode/sqlite3": true
  esbuild: true
  msnodesqlv8: true
  puppeteer: true
  "@tailwindcss/oxide": true
  sharp: true

overrides:
  tailwindcss>nanoid: "3.3.7"

patchedDependencies:
  "@capacitor/camera@8.2.0": patches/@capacitor__camera@8.2.0.patch
  "@capacitor/filesystem@8.1.2": patches/@capacitor__filesystem@8.1.2.patch
  "@capacitor/geolocation@8.2.0": patches/@capacitor__geolocation@8.2.0.patch
