-- PAJRNRCVH ACTUAL SQL Server Schema
-- Run this to verify real table structure

-- 1. Get all columns with their REAL types
SELECT
  COLUMN_NAME,
  DATA_TYPE,
  IS_NULLABLE,
  COLUMN_DEFAULT,
  COLUMNPROPERTY(COLUMN_NAME, 'IsIdentity'),
  COLUMNPROPERTY(COLUMN_NAME, 'IsComputed')
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
ORDER BY ORDINAL_POSITION;

-- 2. Identify identity columns (NOT NULLABLE)
SELECT
  COLUMN_NAME,
  IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND IS_NULLABLE = 'NO';

-- 3. Count identity columns
SELECT COUNT(*) AS identity_column_count
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND COLUMNPROPERTY(COLUMN_NAME, 'IsIdentity') = 1;

-- 4. Sample recent rows for reference
SELECT TOP 5 PAT_CD, NAM, SHIFT, BIRTH, AGE, GEND, TEL1, ADDR, IDNO, PAY, DUE, DISC_VL, DRS_CD, SRV_CD, TR_NO, VST_DT, ENTRYDATE, UPDATEDATE, PAT_STS, VST_NO, VST_DT, VST_DT_AM, ISDT, ISDT_ENTRY, ISDT_ENTRY_AM
FROM op2026.dbo.PAJRNRCVH
ORDER BY UPDATEDATE DESC;

-- 5. Get DEFAULT constraints (if any)
SELECT
  COLUMN_NAME,
  COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND COLUMN_DEFAULT IS NOT NULL;
