-- SQL Server Metadata Inspection for PAJRNRCVH
-- Run: node scripts/inspect-db-metadata.js

-- Tables and their key columns:

SELECT
  TABLE_NAME = 'op2026.dbo.PAJRNRCVH',
  COLUMN_NAME,
  COLUMNPROPERTY(Column_Name, 'IsIdentity'),
  COLUMNPROPERTY(Column_Name, 'AllowsNull'),
  COLUMNPROPERTY(Column_Name, 'IsComputed'),
  COLUMNPROPERTY(Column_Name, 'IsNullable'),
  DATA_TYPE,
  CHARACTER_MAXIMUM_LENGTH,
  IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
ORDER BY TABLE_NAME, COLUMN_NAME;

-- Check for NOT NULL constraint:
SELECT
  TABLE_NAME = 'op2026.dbo.PAJRNRCVH',
  COLUMN_NAME,
  IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND IS_NULLABLE = 'NO';

-- Check for DEFAULT constraints:
SELECT
  TABLE_NAME = 'op2026.dbo.PAJRNRCVH',
  COLUMN_NAME,
  COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
ORDER BY COLUMN_NAME;

-- Check computed columns:
SELECT
  TABLE_NAME = 'op2026.dbo.PAJRNRCVH',
  COLUMN_NAME,
  COLUMNPROPERTY(Column_Name, 'IsComputed')
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND COLUMNPROPERTY(Column_Name, 'IsComputed') = 1;

-- Check identity columns:
SELECT
  TABLE_NAME = 'op2026.dbo.PAJRNRCVH',
  COLUMN_NAME,
  COLUMNPROPERTY(Column_Name, 'IsIdentity')
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'op2026.dbo.PAJRNRCVH'
  AND COLUMNPROPERTY(Column_Name, 'IsIdentity') = 1;

-- Sample row count and recent entries:
SELECT TOP 10 PAT_CD, NAM, TR_NO, TR_TY, PRNTD, PRNTD1, ENTRYDATE, UPDATEDATE
FROM op2026.dbo.PAJRNRCVH
ORDER BY UPDATEDATE DESC;

-- Check for PAPAT_SRV linkage:
SELECT TOP 1 * FROM op2026.dbo.PAPAT_SRV;
