CREATE TABLE `appointments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int,
	`appointmentDate` timestamp NOT NULL,
	`appointmentType` enum('examination','surgery','followup') NOT NULL,
	`branch` enum('examinations','surgery') NOT NULL,
	`status` enum('scheduled','completed','cancelled','no_show') DEFAULT 'scheduled',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `appointments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `auditLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`action` varchar(255) NOT NULL,
	`entityType` varchar(100) NOT NULL,
	`entityId` int,
	`details` text,
	`ipAddress` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consentForms` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`surgeryId` int,
	`formType` enum('lasik_consent','cataract_consent','general_consent') NOT NULL,
	`consentText` text,
	`patientSignature` text,
	`guardianName` varchar(255),
	`guardianSignature` text,
	`signedDate` timestamp,
	`isAccepted` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consentForms_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `doctorReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitId` int NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int NOT NULL,
	`diagnosis` text NOT NULL,
	`clinicalOpinion` text,
	`recommendedTreatment` text,
	`surgeryType` enum('PRK_surface','LASIK_subsurface','Femtolasik','Wavefront','Detailed','Cataract_American','Cataract_Indian','IOL','ICL','Corneal_fixation','Strabismus','Glaucoma','Yag_laser','other'),
	`surgeryScheduledDate` date,
	`additionalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `doctorReports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `examinations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitId` int NOT NULL,
	`patientId` int NOT NULL,
	`ucvaOD` varchar(20),
	`ucvaOS` varchar(20),
	`bcvaOD` varchar(20),
	`bcvaOS` varchar(20),
	`refOD_S` decimal(5,2),
	`refOD_C` decimal(5,2),
	`refOD_A` decimal(5,2),
	`refOS_S` decimal(5,2),
	`refOS_C` decimal(5,2),
	`refOS_A` decimal(5,2),
	`butOD` varchar(20),
	`butOS` varchar(20),
	`schirmerOD` varchar(20),
	`schirmerOS` varchar(20),
	`lidMarginOD` varchar(20),
	`lidMarginOS` varchar(20),
	`iopOD` decimal(5,2),
	`iopOS` decimal(5,2),
	`fundusOD` text,
	`fundusOS` text,
	`dominantEye` enum('OD','OS'),
	`examinationNotes` text,
	`examinedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `examinations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `medicalHistoryChecklist` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitId` int NOT NULL,
	`patientId` int NOT NULL,
	`generalDiseases` text,
	`eyeDiseases` text,
	`isPregnant` boolean,
	`pregnancyTrimester` varchar(50),
	`usesAcneMedication` boolean,
	`acneMedicationName` varchar(255),
	`familyHistoryKeratoconus` boolean,
	`usesTearSupplements` boolean,
	`hasExcessiveTearing` boolean,
	`hasSandyFeeling` boolean,
	`symptomsWithACHeating` boolean,
	`treatsAllergyDryEye` boolean,
	`treatsGlaucoma` boolean,
	`recordedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `medicalHistoryChecklist_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `patients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientCode` varchar(50) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`dateOfBirth` date,
	`age` int,
	`gender` enum('male','female'),
	`nationalId` varchar(20),
	`phone` varchar(20),
	`alternatePhone` varchar(20),
	`address` text,
	`occupation` varchar(255),
	`referralSource` varchar(255),
	`medicalHistory` text,
	`allergies` text,
	`branch` enum('examinations','surgery') DEFAULT 'examinations',
	`status` enum('new','followup','archived') DEFAULT 'new',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patients_id` PRIMARY KEY(`id`),
	CONSTRAINT `patients_patientCode_unique` UNIQUE(`patientCode`)
);
--> statement-breakpoint
CREATE TABLE `pentacamResults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitId` int NOT NULL,
	`patientId` int NOT NULL,
	`ltK1` decimal(6,3),
	`ltK2` decimal(6,3),
	`ltAX` decimal(5,2),
	`ltThinnestPoint` decimal(6,2),
	`ltCornealApex` decimal(6,3),
	`ltResidualStroma` decimal(6,2),
	`ltPlannedTTT` decimal(6,2),
	`ltAblation` decimal(6,2),
	`rtK1` decimal(6,3),
	`rtK2` decimal(6,3),
	`rtAX` decimal(5,2),
	`rtThinnestPoint` decimal(6,2),
	`rtCornealApex` decimal(6,3),
	`rtResidualStroma` decimal(6,2),
	`rtPlannedTTT` decimal(6,2),
	`rtAblation` decimal(6,2),
	`techniciansNotes` text,
	`recordedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pentacamResults_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `postOpFollowups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`surgeryId` int NOT NULL,
	`patientId` int NOT NULL,
	`followupDate` timestamp NOT NULL,
	`daysPostOp` int,
	`postOpUCVA_OD` varchar(20),
	`postOpUCVA_OS` varchar(20),
	`postOpBCVA_OD` varchar(20),
	`postOpBCVA_OS` varchar(20),
	`postOpRefraction_OD_S` decimal(5,2),
	`postOpRefraction_OD_C` decimal(5,2),
	`postOpRefraction_OD_A` decimal(5,2),
	`postOpRefraction_OS_S` decimal(5,2),
	`postOpRefraction_OS_C` decimal(5,2),
	`postOpRefraction_OS_A` decimal(5,2),
	`postOpK1_OD` decimal(6,3),
	`postOpK1_OS` decimal(6,3),
	`postOpK2_OD` decimal(6,3),
	`postOpK2_OS` decimal(6,3),
	`postOpIOP_OD` decimal(5,2),
	`postOpIOP_OS` decimal(5,2),
	`clinicalFindings` text,
	`complications` text,
	`treatmentGiven` text,
	`doctorId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `postOpFollowups_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `prescriptions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`visitId` int NOT NULL,
	`patientId` int NOT NULL,
	`doctorId` int NOT NULL,
	`medicationName` varchar(255) NOT NULL,
	`dosage` varchar(100) NOT NULL,
	`frequency` varchar(100),
	`duration` varchar(100),
	`instructions` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `prescriptions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `surgeries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`appointmentId` int,
	`doctorId` int NOT NULL,
	`surgeryType` enum('PRK_surface','LASIK_subsurface','Femtolasik','Wavefront','Detailed','Cataract_American','Cataract_Indian','IOL','ICL','Corneal_fixation','Strabismus','Glaucoma','Yag_laser','other') NOT NULL,
	`surgeryDate` timestamp NOT NULL,
	`preOpUCVA_OD` varchar(20),
	`preOpUCVA_OS` varchar(20),
	`preOpBCVA_OD` varchar(20),
	`preOpBCVA_OS` varchar(20),
	`preOpRefraction_OD_S` decimal(5,2),
	`preOpRefraction_OD_C` decimal(5,2),
	`preOpRefraction_OD_A` decimal(5,2),
	`preOpRefraction_OS_S` decimal(5,2),
	`preOpRefraction_OS_C` decimal(5,2),
	`preOpRefraction_OS_A` decimal(5,2),
	`beforeFlapK1_OD` decimal(6,3),
	`beforeFlapK1_OS` decimal(6,3),
	`beforeFlapK2_OD` decimal(6,3),
	`beforeFlapK2_OS` decimal(6,3),
	`afterFlapK1_OD` decimal(6,3),
	`afterFlapK1_OS` decimal(6,3),
	`afterFlapK2_OD` decimal(6,3),
	`afterFlapK2_OS` decimal(6,3),
	`afterTreatmentRefraction_OD_S` decimal(5,2),
	`afterTreatmentRefraction_OD_C` decimal(5,2),
	`afterTreatmentRefraction_OD_A` decimal(5,2),
	`afterTreatmentRefraction_OS_S` decimal(5,2),
	`afterTreatmentRefraction_OS_C` decimal(5,2),
	`afterTreatmentRefraction_OS_A` decimal(5,2),
	`afterFlapRepositionK1_OD` decimal(6,3),
	`afterFlapRepositionK1_OS` decimal(6,3),
	`afterFlapRepositionK2_OD` decimal(6,3),
	`afterFlapRepositionK2_OS` decimal(6,3),
	`cicloCount` int,
	`surgeryNotes` text,
	`complications` text,
	`status` enum('scheduled','completed','cancelled') DEFAULT 'scheduled',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `surgeries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `visits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`patientId` int NOT NULL,
	`appointmentId` int,
	`visitDate` timestamp NOT NULL DEFAULT (now()),
	`visitType` enum('consultation','examination','surgery','followup') NOT NULL,
	`chiefComplaint` text,
	`branch` enum('examinations','surgery') NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `visits_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('admin','doctor','nurse','technician','reception','manager') NOT NULL DEFAULT 'reception';--> statement-breakpoint
ALTER TABLE `users` ADD `branch` enum('examinations','surgery','both') DEFAULT 'examinations' NOT NULL;--> statement-breakpoint
ALTER TABLE `users` ADD `isActive` boolean DEFAULT true NOT NULL;