directories:
  output: E:\selrs.cc\desktop-electron
  buildResources: build
appId: cc.selrs.electron
productName: SELRS
files:
  - filter:
      - main.js
      - preload.js
      - dist/**/*
publish:
  provider: generic
  url: http://192.168.1.100:4000/updates
win:
  icon: assets/app.ico
  target:
    - target: nsis
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SELRS
  installerIcon: assets/app.ico
  uninstallerIcon: assets/app.ico
  installerHeaderIcon: assets/app.ico
  artifactName: SELRS-Electron-Setup-${version}.${ext}
electronVersion: 44.4.3
